# Generated by Django 3.1.4 on 2021-02-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_auto_20210215_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
